### ISSUE TITLE
link to lessons directs to current workshop page

### ISSUE THREAD

**Issue by raynamharris** [ChristinaLK/2016-09-28-ttt-sesync#1]
Under the section "Schedule" on the main page is says: "Please see the course materials website for course material." However, when you click the hyperlinked "course materials" you are taken to the current page rather (which is specific to the current workshop) rather than being taken to http://swcarpentry.github.io/instructor-training/

I don't know how to change the redirect because its coded with "Please see <a href="{{site.swc_it_site}}">the course materials website</a> for course material."

**Comment by ChristinaLK** [comment]
Good catch - is fixed.
